version: 2.1


# commands:
#   echo-command:
#     steps:
# 

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  echo-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "mything"

workflows:
  my-workflow:
    jobs:
      - hello-job
  second-workflow:
    jobs:
      - echo-job